WX_KEY_MSGID = 'MsgId'
WX_KEY_FROMUSERNAME = 'FromUserName'
WX_KEY_TOUSERNAME = 'ToUserName'
WX_KEY_MSGTYPE = 'MsgType'
WX_KEY_CONTENT = 'Content'
WX_KEY_STATUS = 'Status'
WX_KEY_IMGSTATUS = 'ImgStatus'
WX_KEY_CREATETIME = 'CreateTime'
WX_KEY_VOICELENGTH = 'VoiceLength'
WX_KEY_PLAYLENGTH = 'PlayLength'
WX_KEY_FILENAME = 'FileName'
WX_KEY_FILESIZE = 'FileSize'
WX_KEY_MEDIAID = 'MediaId'
WX_KEY_URL = 'Url'
WX_KEY_APPMSGTYPE = 'AppMsgType'
WX_KEY_STATUSNOTIFYCODE = 'StatusNotifyCode'
WX_KEY_STATUSNOTIFYUSERNAME = 'StatusNotifyUserName'
WX_KEY_FORWARDFLAG = 'ForwardFlag'
WX_KEY_HASPRODUCTID = 'HasProductId'
WX_KEY_TICKET = 'Ticket'
WX_KEY_IMGHEIGHT = 'ImgHeight'
WX_KEY_IMGWIDTH = 'ImgWidth'
WX_KEY_SUBMSGTYPE = 'SubMsgType'
WX_KEY_NEWMSGID = 'NewMsgId'
WX_KEY_ORICONTENT = 'OriContent'
WX_KEY_ENCRYFILENAME = 'EncryFileName'
WX_KEY_USER = 'User'
WX_KEY_USERNAME = 'UserName'
WX_KEY_NICKNAME = 'NickName'
WX_KEY_SEX = 'Sex'
WX_KEY_HEADIMGUPDATEFLAG = 'HeadImgUpdateFlag'
WX_KEY_CONTACTTYPE = 'ContactType'
WX_KEY_ALIAS = 'Alias'
WX_KEY_CHATROOMOWNER = 'ChatRoomOwner'
WX_KEY_HEADIMGURL = 'HeadImgUrl'
WX_KEY_CONTACTFLAG = 'ContactFlag'
WX_KEY_MEMBERCOUNT = 'MemberCount'
WX_KEY_HIDEINPUTBARFLAG = 'HideInputBarFlag'
WX_KEY_SIGNATURE = 'Signature'
WX_KEY_VERIFYFLAG = 'VerifyFlag'
WX_KEY_REMARKNAME = 'RemarkName'
WX_KEY_STATUES = 'Statues'
WX_KEY_ATTRSTATUS = 'AttrStatus'
WX_KEY_PROVINCE = 'Province'
WX_KEY_SNSFLAG = 'SnsFlag'
WX_KEY_KEYWORD = 'KeyWord'
WX_KEY_TYPE = 'Type'
WX_KEY_TEXT = 'Text'
WX_KEY_RECOMMENDINFO = 'RecommendInfo'
WX_KEY_APPINFO = 'AppInfo'
WX_KEY_CITY = 'City'
WX_KEY_ACTUALNICKNAME = 'ActualNickName'

MSG_KEY = [WX_KEY_MSGID, WX_KEY_FROMUSERNAME, WX_KEY_TOUSERNAME, WX_KEY_MSGTYPE, WX_KEY_CONTENT, WX_KEY_STATUS,
           WX_KEY_IMGSTATUS, WX_KEY_CREATETIME, WX_KEY_VOICELENGTH, WX_KEY_PLAYLENGTH,
           WX_KEY_FILENAME, WX_KEY_FILESIZE, WX_KEY_MEDIAID, WX_KEY_URL, WX_KEY_APPMSGTYPE, WX_KEY_STATUSNOTIFYCODE,
           WX_KEY_STATUSNOTIFYUSERNAME, WX_KEY_FORWARDFLAG,
           WX_KEY_HASPRODUCTID, WX_KEY_TICKET, WX_KEY_IMGHEIGHT, WX_KEY_IMGWIDTH, WX_KEY_SUBMSGTYPE, WX_KEY_NEWMSGID,
           WX_KEY_ORICONTENT, WX_KEY_ENCRYFILENAME,
           WX_KEY_USER, WX_KEY_USERNAME, WX_KEY_NICKNAME, WX_KEY_SEX, WX_KEY_HEADIMGUPDATEFLAG, WX_KEY_CONTACTTYPE,
           WX_KEY_ALIAS, WX_KEY_CHATROOMOWNER, WX_KEY_HEADIMGURL,
           WX_KEY_CONTACTFLAG, WX_KEY_MEMBERCOUNT, WX_KEY_HIDEINPUTBARFLAG, WX_KEY_SIGNATURE, WX_KEY_VERIFYFLAG,
           WX_KEY_REMARKNAME, WX_KEY_STATUES, WX_KEY_ATTRSTATUS,
           WX_KEY_PROVINCE, WX_KEY_CITY, WX_KEY_SNSFLAG, WX_KEY_KEYWORD, WX_KEY_TYPE, WX_KEY_TEXT, WX_KEY_RECOMMENDINFO,
           WX_KEY_APPINFO, WX_KEY_ACTUALNICKNAME]
